theme: jekyll-theme-cayman
twitter:
  username: U_TIC
defaults:
  - scope:
      path: ""
    values:
      image:
        path: ./image/canada-banner-20200221.png
        height: 1080
        width: 1920
